/** Fort Myers Field Guide: the about page makes the local, family-first reason for the work explicit. */
import { ArrowRight, MapPin } from "lucide-react";
import { Link } from "wouter";
import { PageMeta } from "@/components/PageMeta";
import { SiteShell } from "@/components/SiteShell";

export default function About() {
  return <SiteShell><PageMeta title="About My Huckleberry Life" description="A Fort Myers-based, trust-first resource for home safety, medical alerts, and independent living decisions." path="/about" /><main id="main-content" className="about-page"><section className="section-hero about-hero"><div className="shell about-grid"><div><p className="eyebrow">Fort Myers · The 239</p><h1>Your old friend to the end.</h1><p className="lede">My Huckleberry Life is a trust-first resource for people who want to stay independent at home and the family members trying to help without taking over.</p></div><aside className="about-note"><MapPin aria-hidden="true" /><p>Built in Fort Myers for practical decisions that begin at home: the bathroom, the porch, the bedroom, the car, and the phone that should ring when help is needed.</p></aside></div></section><section className="shell about-statement"><div className="section-kicker"><span>Our job</span><h2>Make the next right question easier to ask.</h2></div><div className="about-copy"><p>Fear makes the internet loud. Medical-alert systems, bathroom safety gear, and connected devices all promise an answer. The real work is slower: look at the home, name the daily routine, read the limits, and pick what someone can actually use.</p><p>Founder <strong>Jeff Archambault</strong> built My Huckleberry Life around that practical standard. The site is for adults 55+ and the adult children helping them make a decision. It is not a medical service, an emergency-response provider, or a shortcut around personal care and planning.</p><blockquote>“If a product needs a long explanation to hide its limits, it does not deserve a quick recommendation.”</blockquote><p>We are starting with home safety and medical alerts because they are the questions families are asking now. The site will grow carefully from there, one sourced guide at a time.</p><Link href="/reviews" className="button">See the review desk <ArrowRight aria-hidden="true" /></Link></div></section></main></SiteShell>;
}
