/** Fort Myers Field Guide: fall-prevention coverage focuses on fit, installation, and clear limits. */
import { Link } from "wouter";
import { PageMeta } from "@/components/PageMeta";
import { SiteShell } from "@/components/SiteShell";
import { FALL_PREVENTION_SOURCE } from "@/lib/reviewData";

export default function FallPrevention() {
  return <SiteShell><PageMeta title="Fall Prevention & Bathroom Safety Guides" description="Practical fall-prevention and bathroom-safety buying guidance for older adults and the people helping them." path="/reviews/fall-prevention" /><main id="main-content" className="reading-page category-page"><div className="reading-shell"><p className="eyebrow">Fall prevention</p><h1>Start with the room and the movement.</h1><p className="page-deck">Bathroom and transfer equipment is not a shortcut around installation, fit, or daily use. We start with what the room asks a person to do.</p><section><h2>What to check before buying</h2><ol className="question-list"><li><strong>Measure the space.</strong><span>Doors, tub walls, toilets, bed frames, and turning space shape what can fit.</span></li><li><strong>Read installation guidance.</strong><span>Wall-mounted safety equipment is only as useful as its attachment and the surface it is attached to.</span></li><li><strong>Check daily handling.</strong><span>Assembly, brakes, folding, cleaning, charging, and adjustment should be simple enough to repeat safely.</span></li><li><strong>Take warnings seriously.</strong><span>Compatibility, entrapment, surface, and weight limits can matter more than a feature list.</span></li></ol></section><section><h2>Practical guides</h2><div className="text-link-list"><Link href="/guides/bathroom-fall-prevention-basics">Bathroom safety starts with the wall, not the catalog.</Link><Link href="/guides/transfer-aid-shopping-checklist">Buy for the transfer, not the product category.</Link><Link href="/checklist">Use the room-by-room home safety checklist.</Link></div></section><section><h2>Evidence context</h2><p>The CDC’s <a href={FALL_PREVENTION_SOURCE} target="_blank" rel="noreferrer">STEADI program</a> provides fall-prevention resources for older adults, caregivers, and providers. A guide cannot evaluate an individual person’s transfer ability or a particular bathroom; seek appropriate qualified guidance when that is a concern.</p></section></div></main></SiteShell>;
}
